# Generated by Django 4.0.3 on 2022-03-21 15:20

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', user.models.ClientManager()),
            ],
        ),
    ]
